### ISSUE TITLE
Asses GraphQL IDL

### ISSUE THREAD

**Issue by trioletas** [ctco-dev/nodejs-graphql-template#32]
Does schema first development make sense?

**Comment by trioletas** [comment]
Port manual GraphQL object schema definition to https://github.com/apollographql/graphql-tools

**Comment by aeldar** [comment]
Created a pull request.
I've added another damn simple resolver just as an example to show resolvers' merging. No tests, no even interfaces, sorry. Please have a look. If it is a right direction, I can make it a little more complex.
